remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
google_analytics: G-FGJKN4HRMN
github:
  zip_url: https://github.com/Svxy/TIPT/releases/download/v1.0/TIPT.zip
  another_url: another value

# i got no idea what im doing with this theme bullshit lmao...